### ISSUE TITLE
How do I properly use roles?

### ISSUE THREAD

**Issue by kutschkem** [khrisrichardson/salt-states#4]
Hi, not sure if this is an issue or not, apart from missing documentation, maybe ;-)

I am trying to set up cloudera-cm5-server with your code, however I seem to be doing something wrong with my grains.

On my salt-client (who is at the same time the salt-master), I put the following in /etc/salt/grains

>roles:
>  - cloudera-cm5-server

Which gets properly picked up by salt as I can see by running grains.items

However the roles module doesn't seem to pick it up, and I get the following errors:

----------                                                                                    
          ID: /etc/cloudera-scm-agent/config.ini                                              
    Function: file.managed                                                                    
      Result: False                                                                           
     Comment: Unable to manage file: Jinja variable 'list' object has no element 0            
     Started: 13:03:38.727162                                                                 
    Duration: 377.063 ms                                                                      
     Changes:                                                                                 
----------                                                                                    
          ID: cloudera-cm5-agent                                                              
    Function: service.running                                                                 
        Name: cloudera-scm-agent                                                              
      Result: False                                                                           
     Comment: One or more requisite failed: cloudera-cm5-agent./etc/cloudera-scm-agent/config.ini                                                                                           
     Started:                                                                                 
    Duration:                                                                                 
     Changes:                                                                                 

In that file the role cloudera-cm5-server is queried, but for nothing is returned.

When I run roles.dict directly against my node, it only returns an empty list. Any clue what could be going wrong here? I would expect to see the roles I assigned in the grains. Roles seem to be a very central concept in your code, mind documenting it a bit more?

Anyway, thanks for this great collection!

**Comment by kutschkem** [comment]
I figured that since you seem to use mine, I have to add a pillar with mine_functions configured to mine grains.item

This is how the file looks like:

    mine_functions:
      grains.item: [roles]

Again, mine.get 'master*' grains.item works and outputs:

    master.adastragrp.com:
        ----------
        master.adastragrp.com:
            ----------
            roles:
                - cloudera-cm5-server

But roles.dict outputs nothing. :-(

**Comment by kutschkem** [comment]
What went wrong is that additionally, roles.dict seems to be dependent on a grain 'environment'. Adding it now makes roles.dict succeed as expected.

**Comment by khrisrichardson** [comment]
@kutschkem Nicely navigated. Yeah, I did neglect to mention that in the documentation. I'm not particularly fond of how that is neither explicit nor flexible.

The intent is to partition roles into namespaces, of which environment was a natural fit. I'm failing to recall why a grain was needed instead of reusing saltenv, but there was a shortcoming for which I couldn't find a suitable workaround at the time, and is probably worth revisiting.

The inflexibility of that design is that one is limited to running a single set of instances for a particular role/service, whereas one may opt to create multiple of the same service within an environment. Kubernetes solves that problem handily with labels. Adding support for labels would be desirable for more flexible discovery.

I'm also not fond of how much this particular design is intrinsically tied to the salt mine, which is dependent on a master. I would prefer to expose other service discovery mechanisms, like SRV records, etcd, consul. Sadly, I haven't had much time to devote to that effort.
