### ISSUE TITLE
Check cloudera-cm5/map.jinja

### ISSUE THREAD

**Issue by kutschkem** [khrisrichardson/salt-states#8]
The GPG-key location looks wrong, it should point to cm5 instead of cdh5.

**Comment by khrisrichardson** [comment]
The keys are identical, and I believe were even lacking from the CM repositories at the time of developing the states.

```
$ wget -O - http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/archive.key 2>/dev/null | md5sum
dc59b632a1ce2ad325c40d0ba4a4927e  -
$ wget -O - http://archive.cloudera.com/cm5/ubuntu/trusty/amd64/cm/archive.key 2>/dev/null | md5sum
dc59b632a1ce2ad325c40d0ba4a4927e  -
```
```
$ wget -O - http://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/RPM-GPG-KEY-cloudera 2>/dev/null | md5sum
bbec9e01525656a96adb5599187e3484  -
$ wget -O - http://archive.cloudera.com/cm5/redhat/6/x86_64/cm/RPM-GPG-KEY-cloudera 2>/dev/null | md5sum
bbec9e01525656a96adb5599187e3484  -
```

I have updated my local branch to reflect the change (since I too cringe at inconsistencies like that), but am in no rush to push the commit if you're okay with that.

P.S. - sorry about the copy/pasta you addressed in your other PR. I had been developing predominantly for ubuntu, and my testing workflow was not particularly amenable to multiple distribution's releases. Since I had upgraded from precise to trusty and Cloudera was not quick to adopt trusty, support of these states fell off my radar. Thanks for giving them some love.

It's also worth noting that I never did complete the custom module for [cloudera](https://github.com/khrisrichardson/salt-states/blob/master/salt/_modules/cloudera.py), nor the corresponding custom [states](https://github.com/khrisrichardson/salt-states/tree/master/salt/_states). I have a vague recollection of the API not exposing methods to perform key steps in the process. Hopefully that has been addressed by now. If you were planning on using those and need some help kicking their development back into gear, let me know.

**Comment by kutschkem** [comment]
;-) I don't mind.

Yes, I plan to use the API for setting things up. For now I am still stuck at just installing the cloudera-scm-server, though. It dies on me without helpful log entries. If you know more, http://stackoverflow.com/questions/30847519/how-do-i-debug-a-failing-cloudera-scm-server-process is the relevant question on SO. I saw that there were a few empty files, but wasn't aware that the cloudera stuff was incomplete. Either way, once the manager actually works, I'll see what is there and what needs some love, at that point I may ask for pointers, thanks for the offer.
